require("moonfit")
console.log("just a simple console log")
console.log("enclose string.format. console wth a list of value: %d", 100)
console.info("just a console info")
console.wran("just a console warn")
return console.error("just a console error")
